### ISSUE TITLE
Can not run ginkgo in Github Action

### ISSUE THREAD

**Issue by DblK** [onsi/ginkgo#1004]
Hi,

I have the following workflow:

```yaml
name: ginkgo

on: 
  push:
    tags-ignore:
      - '**'
    branches:
      - master
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - run: go mod tidy && git diff --exit-code go.mod go.sum

      - name: Install ginkgo
        run: |
          go get github.com/onsi/ginkgo/v2/ginkgo@latest
          go get github.com/onsi/gomega/...
      - name: Verify Go Modules Setup
        run: go mod verify

      # Error
      - name: Print out Ginkgo version
        run: ginkgo version

      - name: Launch tests
        run: ginkgo -r --randomize-all --randomize-suites --race --trace -cover
```

It crashes with the following error:
```
/home/runner/work/_temp/21f61a17-b0aa-4618-bfdd-b8b2a386bcd2.sh: line 1: ginkgo: command not found
Error: Process completed with exit code 127.
```

I can not find out why... any idea?
