### ISSUE TITLE
Unable to Install Ginkgo in Github Actions after Upgrade to Go 1.20

### ISSUE THREAD

**Issue by amanhigh** [onsi/ginkgo#1169]
I had github action which was running on Go 1.19 working fine with ginkgo. However after upgrade to 1.20 it has broken and i am unable to install. Please advise how i can make my Github Action Work. Full Github Action can be found [here](https://github.com/amanhigh/go-fun/blob/master/.github/workflows/build.yml)

_Installation Steps_
```
  export GOPATH=~/go
  export PATH=$PATH:$GOPATH/bin
  go env         
  go get github.com/onsi/ginkgo/v2
  go get github.com/onsi/ginkgo/v2/ginkgo/generators
  go get github.com/onsi/ginkgo/v2/ginkgo/internal
  go get github.com/onsi/ginkgo/v2/ginkgo/labels
  go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
```

- Working Directory is having Go.mod and working fine in Local
- I have tried go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo@latest alone and its also not working.
- I Had to add export's as after upgrading to 1.20 Github setup-go action is no longer setting GOPATH which is required here.

_Error_ (Failure run logs can be found [here](https://github.com/amanhigh/go-fun/actions/runs/4508568972))

```
export GOPATH=~/go
  export PATH=$PATH:$GOPATH/bin
  go env         
  go get github.com/onsi/ginkgo/v2
  go get github.com/onsi/ginkgo/v2/ginkgo/generators
  go get github.com/onsi/ginkgo/v2/ginkgo/internal
  go get github.com/onsi/ginkgo/v2/ginkgo/labels
  go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo <----------------(Fails Here)
  shell: /usr/bin/bash -e {0}
  env:
    GOROOT: /opt/hostedtoolcache/go/1.2.2/x64
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/runner/go"
GORACE=""
GOROOT="/opt/hostedtoolcache/go/1.2.2/x64"
GOTOOLDIR="/opt/hostedtoolcache/go/1.2.2/x64/pkg/tool/linux_amd64"
TERM="dumb"
CC="gcc"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread"
CXX="g++"
CGO_ENABLED="1"
package github.com/onsi/ginkgo/v2
	imports github.com/onsi/ginkgo/v2
	imports github.com/onsi/ginkgo/v2: cannot find package "github.com/onsi/ginkgo/v2" in any of:
	/opt/hostedtoolcache/go/1.2.2/x64/src/pkg/github.com/onsi/ginkgo/v2 (from $GOROOT)
	/home/runner/go/src/github.com/onsi/ginkgo/v2 (from $GOPATH)
```

**Comment by blgm** [comment]
Hi @amanhigh, the steps above differ from the installation instructions: https://onsi.github.io/ginkgo/#installing-ginkgo

Do the documented installation instructions work for you?

**Comment by onsi** [comment]
also - if it helps - this is how gomega runs tests:

https://github.com/onsi/gomega/blob/master/.github/workflows/test.yml

it simply calls `go run github.com/onsi/ginkgo/v2/ginkgo ...`

**Comment by amanhigh** [comment]
> Hi @amanhigh, the steps above differ from the installation instructions: https://onsi.github.io/ginkgo/#installing-ginkgo
> 
> Do the documented installation instructions work for you?

@blgm These instructions were working fine before 1.19 Version of Golang. It broke after upgrade to 1.20.

I tried instructions in link above as well. There also installation fails at
` go install github.com/onsi/ginkgo/v2/ginkgo` step itself. I tried this on a official golang ubuntu image it is working fine. However it doesn't work on github Actions image with Ubuntu as Base.

**Comment by amanhigh** [comment]
> also - if it helps - this is how gomega runs tests:
> 
> https://github.com/onsi/gomega/blob/master/.github/workflows/test.yml
> 
> it simply calls `go run github.com/onsi/ginkgo/v2/ginkgo ...`

@onsi I Checked this out as well. However i am using ginkgo inside goreleaser script which runs test with exclusion etc. Since it was earlier able to install is there any example of github actions which help install it in test container. I also tried apt-get install ginkgo but it gives older version and not ginkgo v2.

**Comment by onsi** [comment]
hey @amanhigh i'll try to take a closer look today - thanks for all the details and especially the link to the repo, makes it much easier to reproduce and understand what's going on.

it really should work to simply change the working directory to `common` and run `go install github.com/onsi/ginkgo/v2/ginkgo`

i did notice that you are using ginkgo v2.8 - can you upgrade to the latest?  in 2.8.2 we added a `tools.go` file to ginkgo that causes go to pull in the CLI's dependencies for you.  after upgrading i would expect this to be enough:

```
- name: Install deps
        working-directory: ./common
        run: go install github.com/onsi/ginkgo/v2/ginkgo
```

that should install Ginkgo in `GOBIN` which should already be on the `PATH`.

Again, i'll try to take a look later today but let me know if you have a chance to try that.

**Comment by onsi** [comment]
yikes! I think I figured it out...

I made a simpler version of your repo structure here:
https://github.com/onsi/multimodule-ginkgo

My first Github action file looked like [this](https://github.com/onsi/multimodule-ginkgo/blob/02e03aa374bfed851e8922bd49238dbb32b08d1e/.github/workflows/test.yml):

```yaml
name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: Install deps
        working-directory: ./common
        run: go install github.com/onsi/ginkgo/v2/ginkgo
      - run: ginkgo -r
```

Which resulted in [this job failure](https://github.com/onsi/multimodule-ginkgo/actions/runs/4519710981/jobs/7960349564) - in particular:
```
can't load package: package github.com/onsi/ginkgo/v2/ginkgo: cannot find package "github.com/onsi/ginkgo/v2/ginkgo" in any of:
[7](https://github.com/onsi/multimodule-ginkgo/actions/runs/4519710981/jobs/7960349564#step:4:8)
	/opt/hostedtoolcache/go/1.2.2/x64/src/pkg/github.com/onsi/ginkgo/v2/ginkgo (from $GOROOT)
[8](https://github.com/onsi/multimodule-ginkgo/actions/runs/4519710981/jobs/7960349564#step:4:9)
	($GOPATH not set)
```

Curious I clicked on "Set up Go" in actions:

```
Setup go version spec 1.2
```

So I changed the [yaml to](https://github.com/onsi/multimodule-ginkgo/blob/main/.github/workflows/test.yml):

```yaml
name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"  //<<<<<<<!!!!!
      - name: Install deps
        working-directory: ./common
        run: go install github.com/onsi/ginkgo/v2/ginkgo
      - run: ginkgo -r
```

and it [passes now](https://github.com/onsi/multimodule-ginkgo/actions/runs/4519714758)!


When Go went from 1.19 to 1.20 the yaml type needed to change from an integer to a string - `1.20` was being interpreted as `1.2` 🤯
