### ISSUE TITLE
Correct usage in TravisCI

### ISSUE THREAD

**Issue by code-ape** [onsi/ginkgo#83]
I've been using Ginkgo for a little while now and really liked it, however I'm struggling to figure out how to use it on TravisCI. My current travis.yml file is:

``` yaml
language: go
go:
  - 1.2

install:
  - go get -d -v -t ./...
  - go build -v ./...
  - go get github.com/onsi/ginkgo/ginkgo

script:
  - go test
  - ginkgo -r
```

This successfully gets Ginkgo as my `go test` runs fine. However the installation doesn't register for in path and `ginkgo -r` fails. Any suggestions?
